"""initial_schema

Revision ID: 5483564880da
Revises: 
Create Date: 2026-09-07 18:00:52.851902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5483564880da'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cameras',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('camera_identifier', sa.String(), nullable=False),
    sa.Column('camera_name', sa.String(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('department', sa.Enum('Police', 'Transport', 'Municipal', 'Admin', name='department_enum'), nullable=False),
    sa.Column('camera_type', sa.Enum('PTZ', 'Fixed Bullet', 'Dome', 'ANPR', name='camera_type_enum'), nullable=False),
    sa.Column('ownership', sa.Enum('Government', 'Private', 'PPP', name='ownership_enum'), nullable=False),
    sa.Column('connectivity_status', sa.Enum('Online', 'Offline', 'Degraded', name='connectivity_status_enum'), nullable=False),
    sa.Column('storage_details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('health_status', sa.Enum('Operational', 'Maintenance Required', 'Defective', name='health_status_enum'), nullable=False),
    sa.Column('installation_date', sa.Date(), nullable=False),
    sa.Column('last_ping', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stream_endpoint', sa.String(), nullable=True),
    sa.Column('registered_by_vendor_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    #op.create_index('idx_cameras_location', 'cameras', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_cameras_camera_identifier'), 'cameras', ['camera_identifier'], unique=True)
    op.create_index(op.f('ix_cameras_camera_type'), 'cameras', ['camera_type'], unique=False)
    op.create_index(op.f('ix_cameras_connectivity_status'), 'cameras', ['connectivity_status'], unique=False)
    op.create_index(op.f('ix_cameras_department'), 'cameras', ['department'], unique=False)
    op.create_index('ix_cameras_department_type', 'cameras', ['department', 'camera_type'], unique=False)
    op.create_index(op.f('ix_cameras_health_status'), 'cameras', ['health_status'], unique=False)
    op.create_index('ix_cameras_location', 'cameras', ['location'], unique=False, postgresql_using='gist')
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('department', sa.Enum('Police', 'Transport', 'Municipal', 'Admin', name='department_enum'), nullable=False),
    sa.Column('role', sa.Enum('admin', 'operator', 'viewer', name='user_role_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_department'), 'users', ['department'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_department'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_cameras_location', table_name='cameras', postgresql_using='gist')
    op.drop_index(op.f('ix_cameras_health_status'), table_name='cameras')
    op.drop_index('ix_cameras_department_type', table_name='cameras')
    op.drop_index(op.f('ix_cameras_department'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_connectivity_status'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_camera_type'), table_name='cameras')
    op.drop_index(op.f('ix_cameras_camera_identifier'), table_name='cameras')
    #op.drop_index('idx_cameras_location', table_name='cameras', postgresql_using='gist')
    op.drop_table('cameras')
    # ### end Alembic commands ###
